import Foundation

enum MotivationalQuotes {
    static let all: [String] = [
        "Get up. Your future isn't going to build itself.",
        "Today is money. Go earn it.",
        "You don't need motivation - you need discipline.",
        "Someone else is already working. Catch up.",
        "You said you wanted more. This is the price.",
        "Win the morning, win the day.",
        "No excuses today. Not one.",
        "Show up tired if you have to. Just show up.",
        "You're not here to be average.",
        "Get uncomfortable. That's where growth is.",
        "The grind doesn't care how you feel.",
        "This is where you separate yourself.",
        "You didn't come this far to slack now.",
        "Be proud tonight - start now.",
        "Do it even if you don't feel like it.",
        "Small wins stack up. Start with this one.",
        "Your goals don't wait - neither should you.",
        "Work now, flex later.",
        "Be the hardest worker in the room.",
        "You control how today goes.",
        "It's early for a reason. Use it.",
        "Most people quit. You won't.",
        "Outwork your competition today.",
        "This is your edge - don't waste it.",
        "Progress > perfection. Move.",
        "Get up and get after it.",
        "One step closer today.",
        "Success starts before sunrise.",
        "Be relentless today.",
        "Don't hit snooze on your future.",
        "Discipline is doing it anyway.",
        "You asked for this life. Earn it.",
        "Push through - you'll thank yourself later.",
        "Comfort is the enemy.",
        "Time to level up.",
        "Show up like a professional.",
        "Stay hungry.",
        "You've got work to do.",
        "No shortcuts today.",
        "Keep building.",
        "This is where champions are made.",
        "The grind starts now.",
        "Be better than yesterday.",
        "Execute. No hesitation.",
        "Stay locked in.",
        "You're capable of more. Prove it.",
        "Attack the day.",
        "Don't waste this morning.",
        "Keep stacking wins.",
        "No one's coming to save you.",
        "Earn your confidence today.",
        "Do the hard things first.",
        "Focus. Execute. Repeat.",
        "Rise and dominate.",
        "Put in the work.",
        "Results come from action.",
        "Stay consistent.",
        "You're building something big.",
        "Don't slow down now.",
        "Effort beats talent today.",
        "Show them what you're about.",
        "Grind now, shine later.",
        "No laziness allowed.",
        "Be disciplined today.",
        "The work matters.",
        "Stay sharp.",
        "Your mindset wins today.",
        "Do more than expected.",
        "Keep pushing forward.",
        "Stay focused.",
        "You're in control.",
        "Show up strong.",
        "No quitting today.",
        "Build momentum.",
        "Lock in.",
        "Stay consistent.",
        "Take action now.",
        "No distractions.",
        "You've got this.",
        "Time to execute.",
        "Don't wait. Start.",
        "Stay disciplined.",
        "Stay hungry.",
        "Push harder.",
        "Be relentless.",
        "Earn your results.",
        "Go all in.",
        "No holding back.",
        "Focus on the goal.",
        "Keep going.",
        "Do the work.",
        "Stay committed.",
        "Be unstoppable.",
        "Grind with purpose.",
        "Stay locked in.",
        "Make it count.",
        "Stay driven.",
        "No excuses.",
        "Rise up.",
        "Stay consistent.",
        "Execute your plan.",
        "Stay motivated.",
        "Push limits.",
        "Work harder.",
        "Stay focused.",
        "No shortcuts.",
        "Stay determined.",
        "Put in effort.",
        "Stay strong.",
        "Keep moving.",
        "Make progress.",
        "Stay disciplined.",
        "Get after it.",
        "Stay focused.",
        "Stay consistent.",
        "Stay driven.",
        "Stay committed.",
        "Keep grinding.",
        "No excuses.",
        "Stay sharp.",
        "Focus up.",
        "Stay on track.",
        "Stay hungry.",
        "Keep pushing.",
        "No quitting.",
        "Stay relentless.",
        "Stay disciplined.",
        "Keep working.",
        "Stay focused.",
        "Keep going.",
        "Stay locked in.",
        "Stay consistent.",
        "Stay driven.",
        "Push forward.",
        "No distractions.",
        "Stay committed.",
        "Stay sharp.",
        "Stay hungry.",
        "Keep building.",
        "Stay relentless.",
        "Stay disciplined.",
        "Stay focused.",
        "Stay driven.",
        "Keep grinding.",
        "Stay consistent.",
        "Stay committed.",
        "Stay sharp.",
        "Stay hungry.",
        "Keep pushing.",
        "Make today count."
    ]

    static func quote(for date: Date) -> String {
        guard !all.isEmpty else { return "" }
        let day = Calendar(identifier: .gregorian).startOfDay(for: date)
        let reference = Calendar(identifier: .gregorian).date(from: DateComponents(year: 2026, month: 1, day: 1)) ?? day
        let dayIndex = Calendar(identifier: .gregorian).dateComponents([.day], from: reference, to: day).day ?? 0
        let index = ((dayIndex % all.count) + all.count) % all.count
        return all[index]
    }
}
